
package codigo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import javax.swing.Timer;
        


public class Ventana_Cornometro extends javax.swing.JFrame {
     
    private Timer tiempo ;   
    private int centesimascegundos =0 , segundos= 0 , minutos =0 , horas =0 ; 
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimascegundos++;  
            
            if (centesimascegundos==100){ // 100 centesimas de segundo es un 1sg
                segundos++; 
                centesimascegundos=0; // y regresa a 0 las centesimas de segundos
            }
            if (segundos==60){ // ah pasado un minuto
                minutos++; 
                segundos=0; 
            }
            if (minutos ==60){
                horas++; 
                minutos=0;
            }
            ActualizarEtiquetaTiempo();
        }
    }; 
    
    private void ActualizarEtiquetaTiempo (){
        String texto = (horas<=9?"0":"")+horas+":"+(minutos<=9?"0":"")+minutos+":"+(segundos<=9?"0":"")+segundos +":"+(centesimascegundos<=9?"0":"")+centesimascegundos;
        // si el horas llega a nueve quiero que pongas un 0 adelante  
        etiquetatime.setText(texto);
    }
    
    
    public Ventana_Cornometro() {
        initComponents(); 
        this.setTitle("CORNOMETRO JAVA ");
        this.setResizable(false); 
        this.setLocationRelativeTo(null); 
        tiempo = new Timer (10,acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cornometro = new javax.swing.JPanel();
        etiquetatime = new javax.swing.JLabel();
        Bcomenzar = new javax.swing.JButton();
        Bpausa = new javax.swing.JButton();
        BStop = new javax.swing.JButton();
        fondoetiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_cornometro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetatime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        etiquetatime.setForeground(new java.awt.Color(0, 0, 0));
        etiquetatime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetatime.setText("00 : 00: 00 : 00");
        etiquetatime.setToolTipText("");
        etiquetatime.setFocusCycleRoot(true);
        panel_cornometro.add(etiquetatime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 120, 40));

        Bcomenzar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Bcomenzar.setText("Comenzar");
        Bcomenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcomenzarActionPerformed(evt);
            }
        });
        panel_cornometro.add(Bcomenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, 30));

        Bpausa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Bpausa.setText("Pausar");
        Bpausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpausaActionPerformed(evt);
            }
        });
        panel_cornometro.add(Bpausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 80, 30));

        BStop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BStop.setText("Resetear");
        BStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BStopActionPerformed(evt);
            }
        });
        panel_cornometro.add(BStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 90, 30));

        fondoetiqueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        panel_cornometro.add(fondoetiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 570, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_cornometro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_cornometro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BStopActionPerformed
      // si el tiempo esta corriendo 
        if (tiempo.isRunning()){
            tiempo.stop(); 
            Bcomenzar.setEnabled(true);
        }
        Bcomenzar.setText("Comenzar"); 
        Bpausa.setEnabled(false); 
        BStop.setEnabled(false);  
        
        
        horas =0 ;  
        minutos=0;  
        segundos=0 ;  
        centesimascegundos=0 ;  
        
        ActualizarEtiquetaTiempo();
    }//GEN-LAST:event_BStopActionPerformed

    private void BpausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpausaActionPerformed
        tiempo.stop(); 
        // habilitar iniciar 
        Bcomenzar.setEnabled(true);  
        Bpausa.setEnabled(false);
    }//GEN-LAST:event_BpausaActionPerformed

    private void BcomenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcomenzarActionPerformed
      // va comenzar que corra el tiempo
        tiempo.start();
        // quiero que no permita volver presionar el boton iniciar
        Bcomenzar.setEnabled(false);
        Bcomenzar.setText("Reanudar"); 
        // ademas quiero que los otros botones esten habilitados 
        Bpausa.setEnabled(true); 
        BStop.setEnabled(true);
        
    }//GEN-LAST:event_BcomenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */ 
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cornometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cornometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cornometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Cornometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Cornometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BStop;
    private javax.swing.JButton Bcomenzar;
    private javax.swing.JButton Bpausa;
    private javax.swing.JLabel etiquetatime;
    private javax.swing.JLabel fondoetiqueta;
    private javax.swing.JPanel panel_cornometro;
    // End of variables declaration//GEN-END:variables
}
